In [ ]:
import torch

# creates a one-dimensional tensor of size 3 filled with 1s
a = torch.ones(3)
a, a[1]

(tensor([1., 1., 1.]), tensor(1.))

In [ ]:
a[1] = 2.0
a

tensor([1., 2., 1.])

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.shape, points[1:], points[1:, :], points[1:, 0]

(torch.Size([3, 2]),
 tensor([[5., 3.],
         [2., 1.]]),
 tensor([[5., 3.],
         [2., 1.]]),
 tensor([5., 2.]))