In [1]:
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]
second_points.storage_offset()

2

In [2]:
second_points.size()

torch.Size([2])

In [ ]:
# stride[i] 表示在内存上 (storage) 沿第 i 维走 1 步要跳过多少元素
points.stride()

# accessing an element i, j in a 2D tensor results in accessing
# the storage_offset + stride[0] * i + stride[1] * j element in the storage

(2, 1)

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [5]:
points_t = points.t()  # shorthand alternative to transpose for two-dimensional tensors
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [7]:
id(points.untyped_storage()) == id(points_t.untyped_storage())

True

In [8]:
points.stride()

(2, 1)

In [9]:
points_t.stride()

(1, 2)

In [10]:
# transposing in higher dimensions 
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [11]:
transpose_t.shape

torch.Size([5, 4, 3])

In [12]:
some_t.stride()

(20, 5, 1)

In [13]:
transpose_t.stride()

(1, 5, 20)

In [14]:
# Contiguous tensors
# Some tensor operations in pytorch only work on contiguous tensors
points.is_contiguous()

True

In [16]:
points_t.is_contiguous()

False

In [17]:
# we can obtain a new contiguous tensor from noncontiguous one using contiguous method
# the content of the tensor will be the same, but the stride will change
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [18]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:

points_t.stride()

(1, 2)

In [20]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [21]:
points_t_cont.stride()

(3, 1)

In [ ]:
# contiguous will make a new reshuffled storage
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [23]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]