In [10]:
import torch
import torch.nn as nn

t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)

# shuffling the elements of a tensor amounts to finding a permutation of its indices
shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]

val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]

train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u

linear_model = nn.Linear(1, 1)
linear_model(val_t_un.unsqueeze(1))

tensor([[1.6981],
        [2.2643]], grad_fn=<AddmmBackward0>)

In [3]:
linear_model.weight

Parameter containing:
tensor([[-0.0381,  0.6634]], requires_grad=True)

In [4]:
linear_model.bias

Parameter containing:
tensor([0.0815], requires_grad=True)

In [6]:
x = torch.ones(1, 2)
linear_model(x)

tensor([[0.7068]], grad_fn=<AddmmBackward0>)